spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/music_metadata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:music}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:music}

spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
